### ISSUE TITLE
WinError 206

### ISSUE THREAD

**Issue by zhouguang0** [guanyingc/SDPS-Net#11]
FileNotFoundError: [WinError 206] 文件名或扩展名太长。: 'data/logdir/UPS_Synth_Dataset\\CVPR2019\\1-11,LCNet,max,adam,cos,ba_h-32,sc_h-128,cr_h-128,in_r-0.0005,no_w-1,di_w-1,in_w-1,in_m-32,di_s-36,in_s-20,in_mask,s1_est_d,s1_est_i,color_aug,int_aug,concat_data\\logdir\\train\\Images'

**Comment by guanyingc** [comment]
Hi,
It seems this error was caused by that the filename was too long, as we saved many important parameters in the filename. You may remove some of the keys from the following lines to reduce the length of filename.

https://github.com/guanyingc/SDPS-Net/blob/a96645365cd444126d67d2a0b65c095b1ba67905/options/base_opts.py#L97-L107
